FROM php:7.0-fpm

ADD ./phalcon.ini /usr/local/etc/php/conf.d
ADD ./phalcon.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    pkg-config \
    libpq-dev \
    libmemcached-dev \
    git \
    curl \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql

# Install Memcached for php 7
RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
    && mkdir -p /tmp/memcached \
    && tar -C /tmp/memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
    && cd /tmp/memcached \
    && ( \
        phpize \
        && ./configure \
        && make \
        && make install ) \
    && docker-php-ext-enable memcached \
    && rm /tmp/memcached.tar.gz \
    && rm -r /tmp/memcached

# Install Redis for PHP
RUN curl -L -o /tmp/redis.tar.gz "https://github.com/phpredis/phpredis/archive/3.0.0.tar.gz" \
    && mkdir -p /tmp/redis \
    && tar -C /tmp/redis -zxvf /tmp/redis.tar.gz --strip 1 \
    && cd /tmp/redis \
    && ( \
        phpize \
        && ./configure \
        && make \
        && make install ) \
    && docker-php-ext-enable redis \
    && rm /tmp/redis.tar.gz \
    && rm -r /tmp/redis

# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Install mongodb driver
RUN pecl install mongodb

#####################################
# Phalcon 3.0.0
#####################################

RUN git clone --depth=1 http://github.com/phalcon/cphalcon -b master /tmp/phalcon \
   && ( \
   cd /tmp/phalcon/build \
   && ./install ) \
   && docker-php-ext-enable phalcon \
   && rm -rf /tmp/phalcon

RUN usermod -u 1000 www-data

WORKDIR /var/www

CMD ["php-fpm"]

EXPOSE 9000
