FROM php:5.6-fpm

ADD ./phalcon.ini /usr/local/etc/php/conf.d
ADD ./phalcon.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    libpq-dev \
    libmemcached-dev \
    curl \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql

# Install memcached
RUN pecl install memcached \
    && docker-php-ext-enable memcached

# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Install mongodb driver
RUN pecl install mongodb

# Install Phalcon
RUN curl -L -o /tmp/phalcon-v2.0.13.tar.gz "https://github.com/phalcon/cphalcon/archive/phalcon-v2.0.13.tar.gz" \
    && mkdir -p /tmp/phalcon \
    && tar -C /tmp/phalcon -zxvf /tmp/phalcon-v2.0.13.tar.gz --strip 1 \
    && rm /tmp/phalcon-v2.0.13.tar.gz \
    && ( \
        cd /tmp/phalcon/ext \
        && phpize \
        && ./configure --enable-phalcon \
        && make -j$(nproc) \
        && make install \
       ) \
    && rm -r /tmp/phalcon \
    && docker-php-ext-enable phalcon

RUN usermod -u 1000 www-data

WORKDIR /var/www/phalcon

CMD ["php-fpm"]

EXPOSE 9000
