FROM php:7.0-fpm

ADD ./phalcon.ini /usr/local/etc/php/conf.d
ADD ./phalcon.pool.conf /usr/local/etc/php-fpm.d/

RUN apt-get update && apt-get install -y \
    pkg-config \
    libpq-dev \
    libmemcached-dev \
    git \
    curl \
    --no-install-recommends \
    && rm -r /var/lib/apt/lists/*

# Install extensions using the helper script provided by the base image
RUN docker-php-ext-install \
    pdo_mysql \
    pdo_pgsql

# Install Memcached for php 7
#RUN curl -L -o /tmp/memcached.tar.gz "https://github.com/php-memcached-dev/php-memcached/archive/php7.tar.gz" \
#    && mkdir -p /usr/src/php/ext/memcached \
#    && tar -C /usr/src/php/ext/memcached -zxvf /tmp/memcached.tar.gz --strip 1 \
#    && docker-php-ext-configure memcached \
#    && docker-php-ext-install memcached \
#    && rm /tmp/memcached.tar.gz

# Install xdebug
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

# Install mongodb driver
RUN pecl install mongodb

#####################################
# Phalcon 3.0.0
#####################################

RUN git clone --depth=5 http://github.com/phalcon/cphalcon -b 3.0.x /tmp/phalcon \
   && ( \
   cd /tmp/phalcon/build \
   && ./install ) \
   && docker-php-ext-enable phalcon \
   && rm -rf /tmp/phalcon

# Install phalcon 2.1.x
#ADD ./phalcon.sh phalcon.sh
#RUN bash phalcon.sh && rm phalcon.sh

RUN usermod -u 1000 www-data

WORKDIR /var/www/phalcon

CMD ["php-fpm"]

EXPOSE 9000
